---
version: "build-{build}"

#os: Windows Server 2012 R2
#platform:
#  - x64

environment:
  machine_user: vagrant
  machine_pass: vagrant
  machine_port: 5985
  KITCHEN_YAML: kitchen.appveyor.yml
  CHEF_LICENSE: accept

branches:
  only:
    - main

# Do not build on tags (GitHub only)
skip_tags: true

# faster cloning
clone_depth: 1

image:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Any CPU

# Install the latest nightly of ChefWorkstation
install:
  - ps: (& cmd /c); iex (irm https://omnitruck.chef.io/install.ps1); Install-Project -Project chef-workstation -channel current
  - ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
  - ps: $PSVersionTable
  - ps: $env:CHEF_LICENSE="accept"
  - ps: secedit /export /cfg $env:temp/export.cfg
  - ps: ((get-content $env:temp/export.cfg) -replace ('PasswordComplexity = 1', 'PasswordComplexity = 0')) | Out-File $env:temp/export.cfg
  - ps: ((get-content $env:temp/export.cfg) -replace ('MinimumPasswordLength = 8', 'MinimumPasswordLength = 0')) | Out-File $env:temp/export.cfg
  - ps: secedit /configure /db $env:windir/security/new.sdb /cfg $env:temp/export.cfg /areas SECURITYPOLICY
  - ps: net user /add $env:machine_user $env:machine_pass
  - ps: net localgroup administrators $env:machine_user /add
  - ps: $env:Path += ";c:\opscode\chef-workstation\bin\"

build_script:
  - ps: c:\opscode\chef-workstation\bin\chef.exe shell-init powershell | iexe; cmd /c c:\opscode\chef-workstation\bin\chef.exe --version

test_script:
  - c:\opscode\chef-workstation\bin\chef.exe exec delivery local all
  - c:\opscode\chef-workstation\bin\chef.exe exec kitchen test --log-level debug

deploy: false
