name             'windows_ad'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'MIT'
description      'Installs/Configures windows active directory'
version          '0.7.2'
source_url       'https://github.com/sous-chefs/windows_ad'
issues_url       'https://github.com/sous-chefs/windows_ad/issues'
supports         'windows', '>= 6.2'
chef_version     '>= 12.1'
