---
name: ci

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@0.0.3

  integration-windows-2016:  # EOL March 15
    needs: lint-unit
    runs-on: windows-2016
    strategy:
      matrix:
        os:
          - 'windows-2016'
        suite:
          - 'default'
          - 'reboot'
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: test-kitchen
        continue-on-error: true
        uses: actionshub/test-kitchen@main
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen_exec.yml
          # ACTIONS_ALLOW_UNSECURE_COMMANDS: true  # allow path editing
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
      - name: "Read file contents"
        uses: andstor/file-reader-action@v1
        with:
          path: "D:/a/windows_ad/windows_ad/.kitchen/reboot-windows-2016-exec-script.ps1"

#  integration-windows-2019:
#    needs: lint-unit
#    runs-on: windows-2019
#    strategy:
#      matrix:
#        os:
#          - 'windows-2019'
#        suite:
#          - 'default'
#          - 'forest'
#      fail-fast: false#

#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2
#      - name: Install Chef
#        uses: actionshub/chef-install@main
#      - name: test-kitchen
#        uses: actionshub/test-kitchen@main
#        env:
#          CHEF_LICENSE: accept-no-persist
#          KITCHEN_LOCAL_YAML: kitchen_exec.yml
#          # ACTIONS_ALLOW_UNSECURE_COMMANDS: true  # allow path editing
#        with:
#          suite: ${{ matrix.suite }}
#          os: ${{ matrix.os }}#

#  integration-windows-2022:
#    needs: lint-unit
#    runs-on: windows-2022
#    strategy:
#      matrix:
#        os:
#          - 'windows-2022'
#        suite:
#          - 'default'
#          - 'forest'
#      fail-fast: false#

#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2
#      - name: Install Chef
#        uses: actionshub/chef-install@main
#      - name: test-kitchen
#        uses: actionshub/test-kitchen@main
#        env:
#          CHEF_LICENSE: accept-no-persist
#          KITCHEN_LOCAL_YAML: kitchen_exec.yml
#          # ACTIONS_ALLOW_UNSECURE_COMMANDS: true  # allow path editing
#        with:
#          suite: ${{ matrix.suite }}
#          os: ${{ matrix.os }}
